## This is the Juju config file, which you can use to specify multiple environments in which to deploy.
## By default Juju ships AWS (default), HP Cloud, OpenStack.
## See https://juju.ubuntu.com/docs for more information

## An environment configuration must always specify at least the following information:
##
## - name (to identify the environment)
## - type (to specify the provider)
## - admin-secret (an arbitrary "password" identifying an client with administrative-level access to system state)

## Values in <brackets> below need to be filled in by the user.

## The default environment is chosen when one is not specified using either:
##   -e, --environment command line parameter
##   JUJU_ENV environment variable
## If both -e and JUJU_ENV are specified, the command line parameter has precedence.
default: local

environments:
  ## https://juju.ubuntu.com/get-started/amazon/
  amazon:
    type: ec2
    admin-secret: 4fff79508c4aac24b39a609b2fd27370
    # globally unique S3 bucket name
    control-bucket: juju-93b50377f5a2edccbb8b5e96a3298d80
    # override if your workstation is running a different series to which you are deploying
    # default-series: precise
    # region defaults to us-east-1, override if required
    # region: us-east-1
    # Usually set via the env variable AWS_ACCESS_KEY_ID, but can be specified here
    # access-key: <secret>
    # Usually set via the env variable AWS_SECRET_ACCESS_KEY, but can be specified here
    # secret-key: <secret>
  
  ## https://juju.ubuntu.com/get-started/openstack/
  openstack:
    type: openstack
    # Specifies whether the use of a floating IP address is required to give the nodes
    # a public IP address. Some installations assign public IP addresses by default without
    # requiring a floating IP address.
    # use-floating-ip: false
    admin-secret: 9e3ba1d6e8a42b4e03cb35e387e8ea3f
    # Globally unique swift bucket name
    control-bucket: juju-6c55d1b3a193cbb2879da88d7dc49864
    # Usually set via the env variable OS_AUTH_URL, but can be specified here
    # auth-url: https://yourkeystoneurl:443/v2.0/
    # override if your workstation is running a different series to which you are deploying
    # default-series: precise
    # The following are used for userpass authentication (the default)
    auth-mode: userpass
    # Usually set via the env variable OS_USERNAME, but can be specified here
    # username: <your username>
    # Usually set via the env variable OS_PASSWORD, but can be specified here
    # password: <secret>
    # Usually set via the env variable OS_TENANT_NAME, but can be specified here
    # tenant-name: <your tenant name>
    # Usually set via the env variable OS_REGION_NAME, but can be specified here
    # region: <your region>
  
  ## https://juju.ubuntu.com/get-started/hp-cloud/
  hpcloud:
    type: openstack
    # Specifies whether the use of a floating IP address is required to give the nodes
    # a public IP address. Some installations assign public IP addresses by default without
    # requiring a floating IP address.
    use-floating-ip: false
    admin-secret: c480409a6e1f63a96353f6532ea595c4
    # Globally unique swift bucket name
    control-bucket: juju-85039db1f0fa1683c5ec398ddb620238
    # Not required if env variable OS_AUTH_URL is set
    auth-url: https://yourkeystoneurl:35357/v2.0/
    # URL denoting a public container holding the juju tools.
    public-bucket-url: https://region-a.geo-1.objects.hpcloudsvc.com/v1/60502529753910
    # override if your workstation is running a different series to which you are deploying
    # default-series: precise
    # The following are used for userpass authentication (the default)
    auth-mode: userpass
    # Usually set via the env variable OS_USERNAME, but can be specified here
    # username: <your username>
    # Usually set via the env variable OS_PASSWORD, but can be specified here
    # password: <secret>
    # Usually set via the env variable OS_TENANT_NAME, but can be specified here
    # tenant-name: <your tenant name>
    # Usually set via the env variable OS_REGION_NAME, but can be specified here
    # region: <your region>
    # The following are used for keypair authentication
    # auth-mode: keypair
    # Usually set via the env variable AWS_ACCESS_KEY_ID, but can be specified here
    # access-key: <secret>
    # Usually set via the env variable AWS_SECRET_ACCESS_KEY, but can be specified here
    # secret-key: <secret>
  
  maas:
    type: maas
    # Change this to where your MAAS server lives.  It must specify the base path.
    maas-server: 'http://192.168.1.1/MAAS/'
    maas-oauth: '<add your OAuth credentials from MAAS here>'
    admin-secret: 85d8ac70a1e436ab0c39f4582f1b4b2d
    default-series: precise
    authorized-keys-path: ~/.ssh/authorized_keys # or any file you want.
    # Or:
    # authorized-keys: ssh-rsa keymaterialhere
  
  ## https://juju.ubuntu.com/get-started/local/
  local:
    type: local
    admin-secret: c987d77a90af454bdd0baa9ab2290c41
    # Override the directory that is used for the storage files and database.
    # The default location is $JUJU_HOME/<ENV>.
    # $JUJU_HOME defaults to ~/.juju
    # root-dir: ~/.juju/local
    # Override the storage port if you have multiple local providers, or if the
    # default port is used by another program.
    # storage-port: 8040
    # Override the shared storage port if you have multiple local providers, or if the
    # default port is used by another program.
    # shared-storage-port: 8041
  
  azure:
    type: azure
    # http://msdn.microsoft.com/en-us/library/windowsazure
    # Windows Azure Management info.
    management-subscription-id: 886413e1-3b8a-5382-9b90-0c9aee199e5d
    management-certificate-path: /home/me/azure.pem
    # Windows Azure Storage info.
    storage-account-name: ghedlkjhw54e
    storage-account-key: fdjh4sfkg
    storage-container-name: sdg50984jmsdf
    # Public Storage info (account name and container name) denoting a public
    # container holding the juju tools.
    # public-storage-account-name: public-storage-account
    # public-storage-container-name: public-storage-container-name
  
  ## https://juju.ubuntu.com/get-started/local/
  hive:
    type: hive
    admin-secret: c987d77a90af454bdd0baa9ab2290c41
    # Override the directory that is used for the storage files and database.
    # The default location is $JUJU_HOME/<ENV>.
    # $JUJU_HOME defaults to ~/.juju
    # root-dir: ~/.juju/local
    # Override the storage port if you have multiple local providers, or if the
    # default port is used by another program.
    # storage-port: 8040
    # Override the shared storage port if you have multiple local providers, or if the
    # default port is used by another program.
    # shared-storage-port: 8041
