## This is the Juju config file, which you can use to specify multiple environments in which to deploy.
## By default Juju ships AWS (default), HP Cloud, OpenStack.
## See https://juju.ubuntu.com/docs for more information

## An environment configuration must always specify at least the following information:
##
## - name (to identify the environment)
## - type (to specify the provider)
## - admin-secret (an arbitrary "password" identifying an client with administrative-level access to system state)

## Values in <brackets> below need to be filled in by the user.

## The default environment is chosen when one is not specified using either:
##   -e, --environment command line parameter
##   JUJU_ENV environment variable
## If both -e and JUJU_ENV are specified, the command line parameter has precedence.
default: hive

environments:
  ## https://juju.ubuntu.com/get-started/local/
  local:
    type: local
    admin-secret: 34ea8cb3637725d1f45e4da3dd00262a
    # Override the directory that is used for the storage files and database.
    # The default location is $JUJU_HOME/<ENV>.
    # $JUJU_HOME defaults to ~/.juju
    # root-dir: ~/.juju/local
    # Override the storage port if you have multiple local providers, or if the
    # default port is used by another program.
    # storage-port: 8040
    # Override the shared storage port if you have multiple local providers, or if the
    # default port is used by another program.
    # shared-storage-port: 8041
  
  ## https://juju.ubuntu.com/get-started/openstack/
  openstack:
    type: openstack
    # Specifies whether the use of a floating IP address is required to give the nodes
    # a public IP address. Some installations assign public IP addresses by default without
    # requiring a floating IP address.
    # use-floating-ip: false
    admin-secret: 6430b51b2a32834359938684025f0e6b
    # Globally unique swift bucket name
    control-bucket: juju-24a5188305aa296f580ba6fa655eff05
    # Usually set via the env variable OS_AUTH_URL, but can be specified here
    # auth-url: https://yourkeystoneurl:443/v2.0/
    # override if your workstation is running a different series to which you are deploying
    # default-series: precise
    # The following are used for userpass authentication (the default)
    auth-mode: userpass
    # Usually set via the env variable OS_USERNAME, but can be specified here
    # username: <your username>
    # Usually set via the env variable OS_PASSWORD, but can be specified here
    # password: <secret>
    # Usually set via the env variable OS_TENANT_NAME, but can be specified here
    # tenant-name: <your tenant name>
    # Usually set via the env variable OS_REGION_NAME, but can be specified here
    # region: <your region>
  
  ## https://juju.ubuntu.com/get-started/hp-cloud/
  hpcloud:
    type: openstack
    # Specifies whether the use of a floating IP address is required to give the nodes
    # a public IP address. Some installations assign public IP addresses by default without
    # requiring a floating IP address.
    use-floating-ip: false
    admin-secret: 72f5603a5e4f0cf2cd773ebf6db96a65
    # Globally unique swift bucket name
    control-bucket: juju-dbe76f4db85f18342b1db11bbafd3e49
    # Not required if env variable OS_AUTH_URL is set
    auth-url: https://yourkeystoneurl:35357/v2.0/
    # URL denoting a public container holding the juju tools.
    public-bucket-url: https://region-a.geo-1.objects.hpcloudsvc.com/v1/60502529753910
    # override if your workstation is running a different series to which you are deploying
    # default-series: precise
    # The following are used for userpass authentication (the default)
    auth-mode: userpass
    # Usually set via the env variable OS_USERNAME, but can be specified here
    # username: <your username>
    # Usually set via the env variable OS_PASSWORD, but can be specified here
    # password: <secret>
    # Usually set via the env variable OS_TENANT_NAME, but can be specified here
    # tenant-name: <your tenant name>
    # Usually set via the env variable OS_REGION_NAME, but can be specified here
    # region: <your region>
    # The following are used for keypair authentication
    # auth-mode: keypair
    # Usually set via the env variable AWS_ACCESS_KEY_ID, but can be specified here
    # access-key: <secret>
    # Usually set via the env variable AWS_SECRET_ACCESS_KEY, but can be specified here
    # secret-key: <secret>
  
  maas:
    type: maas
    # Change this to where your MAAS server lives.  It must specify the base path.
    maas-server: 'http://192.168.1.1/MAAS/'
    maas-oauth: '<add your OAuth credentials from MAAS here>'
    admin-secret: 0aec96091c0827c73099243ada0d17f5
    default-series: precise
    authorized-keys-path: ~/.ssh/authorized_keys # or any file you want.
    # Or:
    # authorized-keys: ssh-rsa keymaterialhere
  
  ## https://juju.ubuntu.com/get-started/local/
  #local:
    #type: local
    #admin-secret: 7a9a500fbdd52d81735db05e675e767d
    # Override the directory that is used for the storage files and database.
    # The default location is $JUJU_HOME/<ENV>.
    # $JUJU_HOME defaults to ~/.juju
    # root-dir: ~/.juju/local
    # Override the storage port if you have multiple local providers, or if the
    # default port is used by another program.
    # storage-port: 8040
    # Override the shared storage port if you have multiple local providers, or if the
    # default port is used by another program.
    # shared-storage-port: 8041
  
  ## https://juju.ubuntu.com/get-started/amazon/
  amazon:
    type: ec2
    admin-secret: d2982ed820671a45ca68a46bd9db464b
    # globally unique S3 bucket name
    control-bucket: juju-2e411097cb36fb1a16febf3368f56f1f
    # override if your workstation is running a different series to which you are deploying
    # default-series: precise
    # region defaults to us-east-1, override if required
    # region: us-east-1
    # Usually set via the env variable AWS_ACCESS_KEY_ID, but can be specified here
    # access-key: <secret>
    # Usually set via the env variable AWS_SECRET_ACCESS_KEY, but can be specified here
    # secret-key: <secret>
  
  azure:
    type: azure
    admin-secret: 74240e9ef31489778b35d5433763b25b
    # Location for instances, e.g. West US, North Europe.
    location: West US
    # http://msdn.microsoft.com/en-us/library/windowsazure
    # Windows Azure Management info.
    management-subscription-id: 886413e1-3b8a-5382-9b90-0c9aee199e5d
    management-certificate-path: /home/me/azure.pem
    # Windows Azure Storage info.
    storage-account-name: ghedlkjhw54e
    # Public Storage info (account name and container name) denoting a public
    # container holding the juju tools.
    # public-storage-account-name: public-storage-account
    # public-storage-container-name: public-storage-container-name
    # Override OS image selection with a fixed image for all deployments.
    # Most useful for developers.
    # force-image-name: b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-13_10-amd64-server-DEVELOPMENT-20130713-Juju_ALPHA-en-us-30GB
    # Pick a simplestreams stream to select OS images from: daily or released
    # images, or any other stream available on simplestreams.  Leave blank for
    # released images.
    # For now, during development, only the daily 13.10 pre-release images work.
    image-stream: daily
    default-series: saucy

  hive:
    type: hive
    admin-secret: 7a9a500fbdd52d81735db05e675e767d
    # Override the directory that is used for the storage files and database.
    # The default location is $JUJU_HOME/<ENV>.
    # $JUJU_HOME defaults to ~/.juju
    # root-dir: ~/.juju/local
    # Override the storage port if you have multiple local providers, or if the
    # default port is used by another program.
    # storage-port: 8040
    # Override the shared storage port if you have multiple local providers, or if the
    # default port is used by another program.
    # shared-storage-port: 8041
