authorized_keys: sshkey1
data_dir: /var/lib/juju
juju_bin: /var/lib/juju/tools/1.2.3-precise-amd64
juju_dl_path: http://foo.com/tools/juju1.2.3-precise-amd64.tgz
juju_version: 1.2.3-precise-amd64
machine_id: "0"
machine_tag: machine-0
provider: dummy
tools_dir: /var/lib/juju/tools/machine-0
update_cache: true
upgrade: "yes"
