---
#- hosts: 172.17.0.8
- hosts: '{{ hosts }}'
  gather_facts: True

  vars_files : 
    - '{{ config_vars }}'
    #- config.yaml

  user: root

  tasks:
    - name: Create admin group
      action: group name=admin gid=1000 system=no

    - name: Create user(s)
      action: user name=ubuntu password=ubuntu group=admin shell=/bin/bash uid=1000

    - name: Install package dependencies
      when: ansible_os_family == "Debian"
      action: apt pkg=$item state=latest update_cache={{ update_cache }}
      with_items:
          - git

    - name: Create required directories
      shell: mkdir -p /var/log/juju 
          {{ data_dir }}/agents/{{ machine_tag }}
          /app
          '{{ juju_bin }}'

    - template: src=/var/lib/juju/ansible/templates/25-juju.j2 dest=/etc/rsyslog.d/25-juju.conf
      #FIXME notify: restart rsyslog service
    - template: src=/var/lib/juju/ansible/templates/jujud-machine.j2 dest=/etc/init/jujud-{{ machine_tag }}.conf
    - template: src=/var/lib/juju/ansible/templates/agent.j2 dest=/var/lib/juju/agents/{{ machine_tag }}/agent.conf

    - name: Fetch juju binaries
      shell: wget --no-verbose -O - '{{ juju_dl_path }}' | tar xz -C '{{ juju_bin }}'
      
    - file: path=/var/lib/juju/agents/{{ machine_tag }}/agent.conf owner=root mode=600
    - file: src={{ juju_bin }} dest={{ tools_dir }} state=link

    #FIXME Hard-coded xavier
    - name: Update authorized keys
      authorized_key: user=ubuntu 
                      key='{{ item }}'
      with_file:
        - /home/xavier/.ssh/id_rsa.pub
      
    - name: Store download path
      shell: echo -n '{{ juju_dl_path }}' > {{ juju_bin }}/downloaded-url.txt
      #FIXME notify: start jujud agent

    #FIXME - name: Import user application into container
      #action: git repo=192.168.0.20:/home/git/python-sample dest=/app depth=1

  handlers:
    - name: restart rsyslog service
      action: service name=rsyslog state=restarted

    - name: start jujud agent 
      #shell: start jujud-machine-1
      #action: service name=jujud-{{ machine_id }} state=restarted
      shell: export JUJU_PROVIDER_TYPE=hive && exec /var/lib/juju/tools/{{ machine_tag  }}/jujud machine 
          --log-file "/var/log/juju/{{ machine_tag  }}.log" --data-dir "/var/lib/juju" 
          --machine-id {{ machine_id  }} --debug >> /var/log/juju/{{ machine_tag  }}.log 2>&1

    - name: reload sshd
      action: service name=ssh state=reloaded
